### ISSUE TITLE
Automatically update daily

### ISSUE THREAD

**Issue by notDavid** [DomT4/homebrew-chromium#2]
Hi, question; do you run the 'brew upgrade domt4/chromium/chromium' manually or have you already made a script (to run daily as a LaunchDaemon) that runs 'brew update', checks if a new version is available, checks whether Chromium is not running and runs 'brew upgrade domt4/chromium/chromium' ?

Thought i'd ask before making a script... /lazy :) if you already have one perhaps you can share it.

Thanks!

**Comment by DomT4** [comment]
Hey @notDavid. I don't _specifically_ have a script to update/upgrade the single formula, but I do use `launchctl` [to ensure](https://github.com/DomT4/homebrew-autoupdate) my Homebrew is updated on system boot and every 24 hours afterwards, which has an optional `upgrade` function attached.

>  checks whether Chromium is not running and runs 'brew upgrade domt4/chromium/chromium' 

It's pretty safe to upgrade even if Chromium is already running and being used. `brew upgrade` won't kill the existing process, and by default the prior version of the formula isn't removed until you explicitly call `brew cleanup`.

Hopefully this helps a bit. Feel free to shout if I can help more at all.

**Comment by notDavid** [comment]
Ahh i see that's good to know i'll be using that, thanks!
