### ISSUE TITLE
Release management clarification

### ISSUE THREAD

**Issue by ardecvz** [DomT4/homebrew-chromium#3]
Hi, Dominyk!

First of all, thank you for your valuable and a little bit tedious work on Homebrew!

Back to the issue, could you clarify this tap's release management? Do you try to stick to stable, beta, dev, or canary releases (I know there's no one-to-one mapping in continuous builds)?

I'm using Chromatic GUI now which isn't ideal as it needs some manual maintenance so I'm seeking an alternative with a stable version compiled by dev source (i.e., no freesmug).

**Comment by DomT4** [comment]
Hey @ardecvz, Thanks for creating the Issue.

I generally try to update once a week to once a fortnight, depending on how hectic things are that week. The update is always the latest snapshot available at the time I do that update. The idea is to be bleeding edge without making people go through the update/upgrade process once every day or two, which when the Chromium download is nearly 70MB can be tedious if you've a slower connection.

Chrome Canary is released generally every night, so it's possible we're usually a bit behind or slightly ahead of that. Yesterday's Canary was at `55.0.2842.0`, and the Chromium in this tap is `55.0.2845.0` as of today.

As you've noted there's not a particularly easy way to work out which Chromium commit links to which Chrome release, but it's safe to say we're much much closer to Canary than anything else.

**Comment by ardecvz** [comment]
I've got it, your current one week release habit seems OK for me as it's indeed too hard to update canary every day; moreover, there's `cask` for latest version.

However, I have a new proposition - split the tap into full release channels.

Have you seen [the official by devs Chromium release schedule](https://omahaproxy.appspot.com/)?

There's `branch_base_position` column which represents the branching point from master for current release and corresponds approximately to the build results from their continuous integration (more info including an official explanation you could find [in my old comment](https://github.com/GRMrGecko/Chromatic/pull/3)).

So if we catch the first successful build in CI after release's `branch_base_position`, we'll can get any current release (stable, beta, etc.) built by devs. Of course, with drawbacks explained at the end of [my comment](https://github.com/GRMrGecko/Chromatic/pull/3).

Are you interested in the split while considering that I may understand something in Chromium releases incorrectly? It should be really handy to have different chromium releases in `brew`. And not only for me.

Anyway, it may be automatized by script if you're interested.

**Comment by ardecvz** [comment]
By the way, you should really add your motto `a bleeding edge version without everyday downloading hassle` in the README because it's a valuable and useful concept in Chromium's canary. IMHO

**Comment by ardecvz** [comment]
I'm closing it now as there's no interest from upstream and I've recently migrated to Linux (yeah, everyone should know :)
If someone was interested in it, you should look at [Chromatic](https://github.com/GRMrGecko/Chromatic) for inspiration.

Anyway, thank you for the repo - it has served my workstation well for these months!

**Comment by DomT4** [comment]
My apologies @ardecvz, I didn't mean to leave you out in the cold here. I quit as a Homebrew maintainer and life stuff has been a bit 🙄 for the last few months so I've really scaled back my time on FOSS stuff.

Hope the migration to Linux works out well for you. Debian with Xfce was always my favourite Linux escape, albeit a somewhat predictable & dull choice I appreciate 😄.
