### ISSUE TITLE
README feedback

### ISSUE THREAD

**Issue by buckyster** [DomT4/homebrew-chromium#4]
When reading the README, I had some questions that you may want to add to the README.

1. Which Chromium channel are you tracking? Stable, Beta, Dev, Canary, latest?

2. Is the preferred way to install using the regular (non-cask) method? It seemed like the regular method could do automated updates? There were no instructions on how to do that in the README, for newbies.  Something like:

```
brew install domt4/chromium/chromium
brew linkapps chromium
brew upgrade
```

**Comment by DomT4** [comment]
Pushed some updates to the README. Let me know if things still aren't clear. Thanks for raising this! 😃
