### ISSUE TITLE
Instruction commands prompt error of non existing pathname

### ISSUE THREAD

**Issue by lljr** [DomT4/homebrew-chromium#8]
OS: Mojave version 10.14.

```bash
brew install domt4/chromium/chromium
```
![screenshot 2018-11-07 14 57 24](https://user-images.githubusercontent.com/36335687/48160489-97d71c00-e29d-11e8-97c9-785e7e982dab.png)

I tried manually `cp -rf /usr/local/opt/chromium/Chromium.app/ /Applications/` and I cannot see the `app` file listed in `/Applications` directory.

**Comment by lljr** [comment]
fix: `cp -rf /usr/local/opt/chromium/Chromium.app /Applications`

**Comment by DomT4** [comment]
You may want to check your Homebrew is up-to-date if you're still seeing the `libexec` path in the `caveats`; that was changed back in https://github.com/DomT4/homebrew-chromium/commit/7cdc9be26360993901abae17f5f91d4574e1c4f0.

**Comment by lljr** [comment]
@DomT4 I see. I followed from the `README.md`.

**Comment by DomT4** [comment]
I completely forgot that was there to be honest, my apologies. I've removed it in https://github.com/DomT4/homebrew-chromium/commit/9dd67ba1d5fb4e616f487d5d945e0dddcc1da202 in favour of just hoping people read the caveats printed after installation, which contain similar instructions.

**Comment by avocadoras** [comment]
@DomT4 don't worry about it. I was multi-tasking when I tried installing the package. I must have forgotten and not read the Caveats section after the installation.
