### ISSUE TITLE
Cask version of Chromium

### ISSUE THREAD

**Issue by miccal** [DomT4/homebrew-chromium#9]
Hello @DomT4, I hope you are well. I am not sure if you remember me, but I was a maintainer of Homebrew Cask when you were a maintainer of Homebrew.

Firstly, I wanted to let you know that the main Cask version of [Chromium](https://github.com/homebrew/homebrew-cask/blob/master/Casks/chromium.rb) is now versioned and has checksum verification.

Secondly, I [recently added](https://github.com/Homebrew/homebrew-cask/pull/81073) a `binary` stanza to the main Cask version like in your own version:
```
binary "#{appdir}/Chromium.app/Contents/MacOS/Chromium", target: 'chromium'
```
but this did not work as expected -- calling `chromium` via bash results in:
```
-bash-5.0.16- /Users/miccal (33) [> chromium
Abort trap: 6
```
and the following dialog appears:

<img width="666" alt="Screen Shot 2020-04-22 at 21 35 59" src="https://user-images.githubusercontent.com/6127163/79988516-53672c80-84e1-11ea-8333-574228055535.png">

I was wondering if you had come across this issue yourself?

Thank you.

**Comment by miccal** [comment]
I have updated the main Cask version of [Chromium](https://github.com/homebrew/homebrew-cask/blob/master/Casks/chromium.rb) with a `shimscript` which has now fixed the above problem of calling `chromium` from the command line.

**Comment by DomT4** [comment]
Hey @miccal! I do indeed remember you; Homebrew always remains a project I'm fond of most of the memories of working on, albeit somewhat relieved to no longer have be such a large part of my life 😄.

Thank you for the various updates here. After the most recent departure from Homebrew I essentially stopped paying attention to the project, so I'm a little reliant on people passing important information down the chain to me.

I've pushed some related commits: https://github.com/DomT4/homebrew-chromium/commit/0b07a2b3b65c93844879e72068bb6daf6a2f8f7d & https://github.com/DomT4/homebrew-chromium/commit/798123b7a0a3fa973208eb0c002f602a48b9ccfe.
